[2024-10-10T04:25:42.016+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-10T04:25:42.086+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mssql_agent_dag.execute_sql_agent_job scheduled__2023-06-30T00:00:00+00:00 [queued]>
[2024-10-10T04:25:42.137+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mssql_agent_dag.execute_sql_agent_job scheduled__2023-06-30T00:00:00+00:00 [queued]>
[2024-10-10T04:25:42.146+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-10-10T04:25:42.708+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): execute_sql_agent_job> on 2023-06-30 00:00:00+00:00
[2024-10-10T04:25:42.912+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1390) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-10T04:25:42.915+0000] {standard_task_runner.py:72} INFO - Started process 1433 to run task
[2024-10-10T04:25:42.914+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mssql_agent_dag', 'execute_sql_agent_job', 'scheduled__2023-06-30T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/mssql_test3.py', '--cfg-path', '/tmp/tmpj8ke7lfg']
[2024-10-10T04:25:42.939+0000] {standard_task_runner.py:105} INFO - Job 89: Subtask execute_sql_agent_job
[2024-10-10T04:25:43.533+0000] {task_command.py:467} INFO - Running <TaskInstance: mssql_agent_dag.execute_sql_agent_job scheduled__2023-06-30T00:00:00+00:00 [running]> on host a4f82a437ff2
[2024-10-10T04:25:45.110+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your@email.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mssql_agent_dag' AIRFLOW_CTX_TASK_ID='execute_sql_agent_job' AIRFLOW_CTX_EXECUTION_DATE='2023-06-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-30T00:00:00+00:00'
[2024-10-10T04:25:45.151+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-10T04:25:45.151+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-10T04:25:45.152+0000] {logging_mixin.py:190} INFO - Current task name:execute_sql_agent_job state:running start_date:2024-10-10 04:25:42.086511+00:00
[2024-10-10T04:25:45.152+0000] {logging_mixin.py:190} INFO - Dag name:mssql_agent_dag and current dag run status:running
[2024-10-10T04:25:45.210+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-10T04:26:01.375+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 650, in pymssql._pymssql.connect
  File "src/pymssql/_mssql.pyx", line 2158, in pymssql._mssql.connect
  File "src/pymssql/_mssql.pyx", line 712, in pymssql._mssql.MSSQLConnection.__init__
  File "src/pymssql/_mssql.pyx", line 1884, in pymssql._mssql.maybe_raise_MSSQLDatabaseException
  File "src/pymssql/_mssql.pyx", line 1901, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (your_server_name)\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mssql_test3.py", line 33, in execute_sql_agent_job
    conn = pymssql.connect(
           ^^^^^^^^^^^^^^^^
  File "src/pymssql/_pymssql.pyx", line 659, in pymssql._pymssql.connect
pymssql.exceptions.OperationalError: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (your_server_name)\n')
[2024-10-10T04:26:01.399+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-10T04:26:01.399+0000] {logging_mixin.py:190} INFO - Task start:2024-10-10 04:25:42.086511+00:00 end:2024-10-10 04:26:01.398069+00:00 duration:19.311558
[2024-10-10T04:26:01.400+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): execute_sql_agent_job> dag:<DAG: mssql_agent_dag> dagrun:<DagRun mssql_agent_dag @ 2023-06-30 00:00:00+00:00: scheduled__2023-06-30T00:00:00+00:00, state:running, queued_at: 2024-10-10 04:24:57.645486+00:00. externally triggered: False>
[2024-10-10T04:26:01.400+0000] {logging_mixin.py:190} INFO - Failure caused by (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (your_server_name)\n')
[2024-10-10T04:26:01.401+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=mssql_agent_dag, task_id=execute_sql_agent_job, run_id=scheduled__2023-06-30T00:00:00+00:00, execution_date=20230630T000000, start_date=20241010T042542, end_date=20241010T042601
[2024-10-10T04:26:01.458+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-10T04:26:01.459+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 89 for task execute_sql_agent_job ((20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (your_server_name)\n'); 1433)
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 650, in pymssql._pymssql.connect
  File "src/pymssql/_mssql.pyx", line 2158, in pymssql._mssql.connect
  File "src/pymssql/_mssql.pyx", line 712, in pymssql._mssql.MSSQLConnection.__init__
  File "src/pymssql/_mssql.pyx", line 1884, in pymssql._mssql.maybe_raise_MSSQLDatabaseException
  File "src/pymssql/_mssql.pyx", line 1901, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (your_server_name)\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mssql_test3.py", line 33, in execute_sql_agent_job
    conn = pymssql.connect(
           ^^^^^^^^^^^^^^^^
  File "src/pymssql/_pymssql.pyx", line 659, in pymssql._pymssql.connect
pymssql.exceptions.OperationalError: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (your_server_name)\n')
[2024-10-10T04:26:01.517+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-10T04:26:01.568+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-10T04:26:01.573+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
