[2024-10-10T04:44:22.241+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-10T04:44:22.573+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mssql_agent_dag.execute_sql_agent_job manual__2024-10-10T04:38:55.744897+00:00 [queued]>
[2024-10-10T04:44:22.685+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mssql_agent_dag.execute_sql_agent_job manual__2024-10-10T04:38:55.744897+00:00 [queued]>
[2024-10-10T04:44:22.690+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-10T04:44:22.906+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): execute_sql_agent_job> on 2024-10-10 04:38:55.744897+00:00
[2024-10-10T04:44:22.977+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1687) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-10T04:44:22.995+0000] {standard_task_runner.py:72} INFO - Started process 1689 to run task
[2024-10-10T04:44:23.010+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mssql_agent_dag', 'execute_sql_agent_job', 'manual__2024-10-10T04:38:55.744897+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/mssql_test3.py', '--cfg-path', '/tmp/tmphzo7kt12']
[2024-10-10T04:44:23.040+0000] {standard_task_runner.py:105} INFO - Job 103: Subtask execute_sql_agent_job
[2024-10-10T04:44:23.803+0000] {task_command.py:467} INFO - Running <TaskInstance: mssql_agent_dag.execute_sql_agent_job manual__2024-10-10T04:38:55.744897+00:00 [running]> on host a4f82a437ff2
[2024-10-10T04:44:25.666+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your@email.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mssql_agent_dag' AIRFLOW_CTX_TASK_ID='execute_sql_agent_job' AIRFLOW_CTX_EXECUTION_DATE='2024-10-10T04:38:55.744897+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-10T04:38:55.744897+00:00'
[2024-10-10T04:44:25.687+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-10T04:44:25.693+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-10T04:44:25.704+0000] {logging_mixin.py:190} INFO - Current task name:execute_sql_agent_job state:running start_date:2024-10-10 04:44:22.578811+00:00
[2024-10-10T04:44:25.710+0000] {logging_mixin.py:190} INFO - Dag name:mssql_agent_dag and current dag run status:running
[2024-10-10T04:44:25.714+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-10T04:44:27.722+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 429, in pymssql._pymssql.Cursor.callproc
  File "src/pymssql/_mssql.pyx", line 1816, in pymssql._mssql.MSSQLStoredProcedure.execute
  File "src/pymssql/_mssql.pyx", line 1855, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1901, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (14262, b"The specified @job_name ('YourAgentJobName') does not exist.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mssql_test3.py", line 43, in execute_sql_agent_job
    cursor.callproc('msdb.dbo.sp_start_job', (job_name,))
  File "src/pymssql/_pymssql.pyx", line 432, in pymssql._pymssql.Cursor.callproc
pymssql.exceptions.DatabaseError: (14262, b"The specified @job_name ('YourAgentJobName') does not exist.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[2024-10-10T04:44:28.040+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-10T04:44:28.057+0000] {logging_mixin.py:190} INFO - Task start:2024-10-10 04:44:22.578811+00:00 end:2024-10-10 04:44:28.021088+00:00 duration:5.442277
[2024-10-10T04:44:28.058+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): execute_sql_agent_job> dag:<DAG: mssql_agent_dag> dagrun:<DagRun mssql_agent_dag @ 2024-10-10 04:38:55.744897+00:00: manual__2024-10-10T04:38:55.744897+00:00, state:running, queued_at: 2024-10-10 04:38:55.758974+00:00. externally triggered: True>
[2024-10-10T04:44:28.082+0000] {logging_mixin.py:190} INFO - Failure caused by (14262, b"The specified @job_name ('YourAgentJobName') does not exist.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[2024-10-10T04:44:28.101+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=mssql_agent_dag, task_id=execute_sql_agent_job, run_id=manual__2024-10-10T04:38:55.744897+00:00, execution_date=20241010T043855, start_date=20241010T044422, end_date=20241010T044428
[2024-10-10T04:44:28.488+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-10T04:44:28.501+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 103 for task execute_sql_agent_job ((14262, b"The specified @job_name ('YourAgentJobName') does not exist.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n"); 1689)
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 429, in pymssql._pymssql.Cursor.callproc
  File "src/pymssql/_mssql.pyx", line 1816, in pymssql._mssql.MSSQLStoredProcedure.execute
  File "src/pymssql/_mssql.pyx", line 1855, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1901, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (14262, b"The specified @job_name ('YourAgentJobName') does not exist.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mssql_test3.py", line 43, in execute_sql_agent_job
    cursor.callproc('msdb.dbo.sp_start_job', (job_name,))
  File "src/pymssql/_pymssql.pyx", line 432, in pymssql._pymssql.Cursor.callproc
pymssql.exceptions.DatabaseError: (14262, b"The specified @job_name ('YourAgentJobName') does not exist.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[2024-10-10T04:44:28.825+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-10T04:44:29.349+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-10T04:44:29.367+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
